"""
Aeoncord - Elegant Discord API client.
"""

from aeoncord.client import ClientConfig, DiscordClient
from aeoncord.core.domain.exceptions import (
    AlreadyConnectedError,
    ChannelNotFoundError,
    DomainError,
    EmptyMessageError,
    EntityNotFoundError,
    InvalidMessageContentError,
    InvalidMessageLengthError,
    InvalidOperationError,
    InvalidStateError,
    MessageAlreadyDeletedError,
    MessageNotFoundError,
    NotChannelOwnerError,
    NotConnectedError,
    NotGuildOwnerError,
    NotMessageAuthorError,
    PermissionDeniedError,
    UserNotFoundError,
)
from aeoncord.core.domain.models import (
    Channel,
    ChannelId,
    Guild,
    GuildId,
    Message,
    MessageCreated,
    MessageDeleted,
    MessageEdited,
    MessageId,
    MessageType,
    ReactionAdded,
    ReactionRemoved,
    Role,
    RoleId,
    Snowflake,
    User,
    UserId,
    UserOffline,
    UserOnline,
)
from aeoncord.events import (
    DisconnectEvent,
    MessageCreateEvent,
    MessageDeleteEvent,
    MessageUpdateEvent,
    ReactionAddEvent,
    ReactionRemoveEvent,
    ReadyEvent,
    ReconnectEvent,
    ResumedEvent,
    UserOfflineEvent,
    UserOnlineEvent,
)

__version__ = "0.1.0"
__author__ = "mrf0rtuna4"
__license__ = "ARR"

__all__ = [
    "AlreadyConnectedError",
    "Channel",
    "ChannelId",
    "ChannelNotFoundError",
    "ClientConfig",
    "DisconnectEvent",
    "DiscordClient",
    "DomainError",
    "EmptyMessageError",
    "EntityNotFoundError",
    "Guild",
    "GuildId",
    "InvalidMessageContentError",
    "InvalidMessageLengthError",
    "InvalidOperationError",
    "InvalidStateError",
    "Message",
    "MessageAlreadyDeletedError",
    "MessageCreateEvent",
    "MessageCreated",
    "MessageDeleteEvent",
    "MessageDeleted",
    "MessageEdited",
    "MessageId",
    "MessageNotFoundError",
    "MessageType",
    "MessageUpdateEvent",
    "NotChannelOwnerError",
    "NotConnectedError",
    "NotGuildOwnerError",
    "NotMessageAuthorError",
    "PermissionDeniedError",
    "ReactionAddEvent",
    "ReactionAdded",
    "ReactionRemoveEvent",
    "ReactionRemoved",
    "ReadyEvent",
    "ReconnectEvent",
    "ResumedEvent",
    "Role",
    "RoleId",
    "Snowflake",
    "User",
    "UserId",
    "UserNotFoundError",
    "UserOffline",
    "UserOfflineEvent",
    "UserOnline",
    "UserOnlineEvent",
]
